language: ruby
rvm:
- 2.2.5
deploy:
  provider: heroku
  api_key:
    secure: IJEN86RHFZhGzqXR512PATrBBoc72KdI97ce3xXK2BMug7rZKNpmD9aD9lYUr23YGeBL0iBGsEJ3QWmyNG/xwNA5j+BEuXdwSIsNMHCoFUMz6V1EYt9us6KH8o8I998Cm/0D1KGUdGz2H738ruH8eaY4V27l2Ux45hFm75zVv/973tHb/Ge0wIkChSV3amLWwZYJJFrpHTDgxGgbV9CBaPY36LRKuaKg3sXltCbVFTloNAXZr3C7+lDxqaFqhT8U916vnsT8tyl1v1e8UR45HrfnCgMh8bdIHU91esWzhyuivR57GojWKv7aFZ2Q7MIjoinvVC7kKKrGWdbRhqyTA9qcOHmWmtMgl6yU8Z4mW2GdNO0YUv77eGNjM1RmbrknndGxTbhd41064BAQvBAXXkpqNzSmcEyTfv8JJCvhWdpzZlniPxFBWIgfLslItre8DbUpN6eViy421RGN9mrOBM2q8EcKLm+nhrQ1hrTdk+fPeG9lU2M14S1DBFWQvgnko86DW5LPIhiFCu7MUCNd86IgwWIAQDvOprye2iKuhXTw0pDSfosBbGgmhACtosnOMErAZIbuKnFoL7JJ48yZ2/IuMkuXQ/CSl+S5XdaJIQ/IFtsSMKiDgfH2fqkP0T9kkUhbBzG+ZykdKD/MdNCKHzb154Cz9n4I8+wQuxo8hJI=
  app: immense-shelf-62833
  on:
    repo: yamdayk/rails_enpit
